apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.30
    path: /k8s-nfs/grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-grafana
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    run: grafana-service
spec:
  type: NodePort
  ports:
    - name: web-port
      protocol: TCP
      port: 3000
      nodePort: 30443
  selector:
    app: grafana

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1 
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana 
        image: grafana/grafana:latest
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: nfs-grafana
            mountPath: "/var/lib/grafana"
      volumes:
      - name: nfs-grafana
        persistentVolumeClaim:
          claimName: nfs-grafana

