apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jumphost-ubuntu
spec:
  selector:
    matchLabels:
      app: jumphost-ubuntu
  replicas: 2 
  template:
    metadata:
      labels:
        app: jumphost-ubuntu
    spec:
      containers:
      - name: jumphost-ubuntu 
        image: een625/emario-ubuntu:latest
        ports:
        - containerPort: 22
--- 
--- kubectl expose deployment/jumphost-ubuntu
kind: Service
apiVersion: v1
metadata:
  name: jumphost-ubuntu-service
  labels:
    run: jumphost-ubuntu-service
spec:
  selector:
    app: jumphost-ubuntu
  ports:
  - protocol: TCP
    port: 10022
    

