apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-telegraf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.30
    path: /k8s-nfs/telegraf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-telegraf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  labels:
    run: telegraf-service
spec:
  type: NodePort
  ports:
    - name: web-port
      protocol: TCP
      port: 22
      nodePort: 30444
  selector:
    app: telegraf

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1 
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf 
        image: telegraf:latest
        ports:
          - containerPort: 22
        volumeMounts:
          - name: nfs-telegraf
            mountPath: "/etc/telegraf"
      volumes:
      - name: nfs-telegraf
        persistentVolumeClaim:
          claimName: nfs-telegraf

