apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-unifi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.30
    path: /k8s-nfs/unifi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-unifi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service
  labels:
    run: unifi-controller-service
spec:
  type: NodePort
  ports:
    - name: web-port
      protocol: TCP
      port: 8443
      nodePort: 31443
    - name: discover-port
      protocol: TCP
      port: 8080
      nodePort: 31444

  selector:
    app: unifi-controller

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: unifi-controller
spec:
  selector:
    matchLabels:
      app: unifi-controller
  replicas: 1 
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - name: unifi-controller 
        image: jacobalberty/unifi:latest
        ports:
          - containerPort: 8443
          - containerPort: 8080
        volumeMounts:
          - name: nfs-unifi 
            mountPath: "/unifi"
      volumes:
      - name: nfs-unifi
        persistentVolumeClaim:
          claimName: nfs-unifi

