---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service
  labels:
    run: unifi-controller-service
spec:
  type: NodePort
  ports:
    - name: web-port
      protocol: TCP
      port: 8443
      nodePort: 38443
  selector:
    app: unifi-controller

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: unifi-controller
spec:
  selector:
    matchLabels:
      app: unifi-controller
  replicas: 1 
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - name: unifi-controller 
        image: jacobalberty/unifi:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: nfs 
          mountPath: /unifi
    volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs

